# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/Code/Pframe/LBFGSpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/Code/Pframe/LBFGSpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Code/Pframe/LBFGSpp/CMakeFiles /home/alex/Code/Pframe/LBFGSpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Code/Pframe/LBFGSpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wtpframe

# Build rule for target.
wtpframe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wtpframe
.PHONY : wtpframe

# fast build rule for target.
wtpframe/fast:
	$(MAKE) -f CMakeFiles/wtpframe.dir/build.make CMakeFiles/wtpframe.dir/build
.PHONY : wtpframe/fast

wtpframe.o: wtpframe.cpp.o

.PHONY : wtpframe.o

# target to build an object file
wtpframe.cpp.o:
	$(MAKE) -f CMakeFiles/wtpframe.dir/build.make CMakeFiles/wtpframe.dir/wtpframe.cpp.o
.PHONY : wtpframe.cpp.o

wtpframe.i: wtpframe.cpp.i

.PHONY : wtpframe.i

# target to preprocess a source file
wtpframe.cpp.i:
	$(MAKE) -f CMakeFiles/wtpframe.dir/build.make CMakeFiles/wtpframe.dir/wtpframe.cpp.i
.PHONY : wtpframe.cpp.i

wtpframe.s: wtpframe.cpp.s

.PHONY : wtpframe.s

# target to generate assembly for a file
wtpframe.cpp.s:
	$(MAKE) -f CMakeFiles/wtpframe.dir/build.make CMakeFiles/wtpframe.dir/wtpframe.cpp.s
.PHONY : wtpframe.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... wtpframe"
	@echo "... edit_cache"
	@echo "... wtpframe.o"
	@echo "... wtpframe.i"
	@echo "... wtpframe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

